# Generated by Django 5.2.3 on 2025-07-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details_image',
            field=models.ImageField(blank=True, help_text='Image showing product details', null=True, upload_to='products/details/'),
        ),
    ]
